### ISSUE TITLE
Failure to find root in hot halo ram pressure stripping

### ISSUE THREAD

**Issue by abensonca** [galacticusorg/galacticus#124]
Very occasionally the Font2008 hot halo ram pressure stripping class will fail because it can not bracket the root for the ram pressure stripping radius. This should never happen because prior to the root finder being called it checks that the ram pressure radius is between the virial radius and the smallest radius considered, and only searches for the root between those two radii. For some reason the sign of the root function changes at one radius between these initially checks and during the root finding.

This does not appear to be a thread conflict (i.e. it happens with MPI code running only 1 OpenMP thread).

**Comment by abensonca** [comment]
Example backtrace:

```
069:M:     virial radius / root function at virial radius = 0.567473E-01 / -.577994E+19 : -.577994E+19
069:M:     small radius / root function at small radius = 0.567473E-07 / 0.306788E+13 : -.322262E+13
Fatal error:
root finding failed
 Occurred at:
     function:font2008RadiusStripped
         file:hot_halo.ram_pressure_stripping.Font2008.F90   [line 199]
  => Error occurred in master thread
#0  0x6cb09d in __galacticus_error_MOD_galacticus_error_report_char
        at ./work/buildMPI/galacticus.error.p.F90:150
#1  0xa0888c in __hot_halo_ram_pressure_stripping_MOD_font2008radiusstripped
        at ./work/buildMPI/hot_halo.ram_pressure_stripping.Font2008.p.F90:436
#2  0xea0bb5 in node_component_hot_halo_standard_outer_radius_growth_rate
        at ./work/buildMPI/objects.nodes.components.hot_halo.standard.p.F90:2195
#3  0x1047c58 in __galacticus_nodes_MOD_hothalostandardouterradiusgrowthrate
        at /home/abenson/Galacticus/galacticus_search/<stdin>:57555
#4  0x1047c58 in __galacticus_nodes_MOD_hothalocoldmodeouterradiusgrowthrate
        at /home/abenson/Galacticus/galacticus_search/<stdin>:55114
#5  0x1047c58 in __galacticus_nodes_MOD_hothalocoldmodeouterradiusgrowthrate
        at /home/abenson/Galacticus/galacticus_search/<stdin>:55100
#6  0xe9cc53 in __node_component_hot_halo_cold_mode_MOD_node_component_hot_halo_cold_mode_rate_compute
        at ./work/buildMPI/objects.nodes.components.hot_halo.cold_mode.p.F90:677
#7  0xbe23b5 in __merger_trees_evolve_node.mergertreenodeevolverstandard__MOD_standardderivativescompute
        at /home/abenson/Galacticus/galacticus_search/<stdin>:21
#8  0xbe3673 in __merger_trees_evolve_node.mergertreenodeevolverstandard__MOD_standardodes
        at ./work/buildMPI/merger_trees.node_evolver.standard.p.F90:1431
#9  0xe16016 in derivativeswrapper
        at ./work/buildMPI/numerical.ODE_solver.p.F90:752
#10  0x7f9bd48ceb22 in rkck_apply
        at /data001/abenson/Galacticus/Tools/gsl-1.16/ode-initval2/rkck.c:304
#11  0x7f9bd48c8a35 in gsl_odeiv2_step_apply
        at /data001/abenson/Galacticus/Tools/gsl-1.16/ode-initval2/step.c:73
#12  0x7f9bd48c843f in gsl_odeiv2_evolve_apply
        at /data001/abenson/Galacticus/Tools/gsl-1.16/ode-initval2/evolve.c:182
#13  0x9c2915 in gsl_odeiv2_driver2_apply
        at source/gslODEInitVal2/driver2.c:192
#14  0xe16772 in __numerical_ode_solvers_MOD_odesolversolve
        at ./work/buildMPI/numerical.ODE_solver.p.F90:620
#15  0xbe7b45 in __merger_trees_evolve_node_MOD_standardevolve
        at ./work/buildMPI/merger_trees.node_evolver.standard.p.F90:1163
#16  0xbcf2e1 in __merger_trees_evolve_MOD_standardevolve
        at ./work/buildMPI/merger_trees.evolver.standard.p.F90:735
#17  0x14ed4b3 in __tasks_MOD_evolveforestsperform._omp_fn.0
        at ./work/buildMPI/tasks.evolve_forests.p.F90:1363
#18  0x7f9bd2575521 in GOMP_parallel
        at ../../../gcc-git/libgomp/parallel.c:171
#19  0x14efeaa in __tasks_MOD_evolveforestsperform
        at ./work/buildMPI/tasks.evolve_forests.p.F90:1025
#20  0xc99ac2 in __models_likelihoods_MOD_galaxypopulationevaluate
        at ./work/buildMPI/models.likelihoods.galaxy_population.p.F90:468
#21  0x10fe3c0 in __posterior_sampling_simulation_MOD_particleswarmposterior
        at ./work/buildMPI/posterior_sampling.simulation.particle_swarm.p.F90:1385
#22  0x11026f8 in __posterior_sampling_simulation_MOD_particleswarmsimulate
        at ./work/buildMPI/posterior_sampling.simulation.particle_swarm.p.F90:1183
#23  0x1572ce6 in __tasks_MOD_posteriorsampleperform
        at ./work/buildMPI/tasks.posterior_sample.p.F90:218
#24  0x443ab7 in galacticus
        at ./work/buildMPI/Galacticus.p.F90:140
#25  0x443cd6 in main
        at ./work/buildMPI/Galacticus.p.F90:30
```

The root function should be +ve at the lower radius (and it initially is: 0.306788E+13), but during root finding changes to be -ve (-.322262E+13).

Currently running with some extra debugging output to try to determine what changes (enclosed mass or hot halo density).
